# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 02:56
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='like',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='secret',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
