# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_auto_20170621_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
