# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 01:50
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_auto_20170622_2023'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
