# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 01:53
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_auto_20170622_2050'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
