# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 02:47
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_auto_20170625_1536'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
