# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_auto_20170626_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app_main.User'),
            preserve_default=False,
        ),
    ]
