# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='app_main.User'),
            preserve_default=False,
        ),
    ]
