# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_comment_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_profile',
        ),
    ]
